---
- name: OS check
  debug:
    msg: "Detected OS Family: {{ ansible_facts['os_family'] }}"
- name: Setup identity on Debian based systems
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Setup identity on RedHat based systems
  ansible.builtin.include_tasks: setup-RedHat.yaml
  when: ansible_facts['os_family'] == "RedHat"
